title: <p align="center"> Vikash Ankit </p>
logo: /assets/img/logo.png
description:
  <p align="center">
  <br>   
  I'm working with CTS as Oracle SQL/PlSQL developer for 3 years.
  I have completed BTECH in 2018 with Infomation Technology.
  Currently a part of JPMC Reulatory Reporting Team and believe to soon be a part of any good Data Science team. :)
  My hobbies are reading books, Coding and learning new things
  <br>
  </p>
show_downloads: true
google_analytics:
theme: jekyll-theme-minimal
